# Generated by Django 4.1.6 on 2023-02-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Usługa hotelowa',
                'verbose_name_plural': 'Usługi hotelowe',
            },
        ),
    ]
