# Generated by Django 4.1.6 on 2023-02-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0002_uslugi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotele',
            name='usluga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotele.uslugi'),
        ),
    ]
