# Generated by Django 4.1.6 on 2023-02-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0003_hotele_usluga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotele',
            name='usluga',
        ),
        migrations.DeleteModel(
            name='Uslugi',
        ),
    ]
