# Generated by Django 4.1.6 on 2023-02-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0005_standard_hotele_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotele',
            name='usluga',
            field=models.ManyToManyField(to='Hotele.uslugi'),
        ),
    ]
