# Generated by Django 4.1.6 on 2023-02-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0006_uslugi_hotele_usluga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uslugi',
            options={'verbose_name': 'Usługa hotelowa', 'verbose_name_plural': 'Usługi hotelowe'},
        ),
    ]
