# Generated by Django 4.1.6 on 2023-02-03 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotele', '0007_alter_uslugi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezerwacjaHotelu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zameldowanie', models.DateField()),
                ('wymeldowanie', models.DateField()),
                ('platnosc', models.CharField(choices=[('prepaid', 'prepaid'), ('postpaid', 'postpaid')], max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotele.hotele')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezerwacje',
            },
        ),
    ]
