# Generated by Django 4.1.6 on 2023-02-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0008_rezerwacjahotelu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacjahotelu',
            options={'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
    ]
