# Generated by Django 4.1.6 on 2023-02-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0009_alter_rezerwacjahotelu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotele',
            name='standard',
        ),
    ]
