# Generated by Django 4.1.6 on 2023-02-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotele', '0010_remove_hotele_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerwacjahotelu',
            old_name='platnosc',
            new_name='rodzaj_platnosci',
        ),
    ]
